{% set name = "uniplot" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uniplot-{{ version }}.tar.gz
  sha256: bb8a6fc513682d7bec6bf41890995aaa04176f230c9cfa71211e8803bbe32abc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22.0

test:
  imports:
    - uniplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/olavolav/uniplot
  summary: Lightweight plotting to the terminal. 4x resolution via Unicode.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
