{% set name = "uniplot" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uniplot-{{ version }}.tar.gz
  sha256: 01883cc7daa616a6cd7226c846014a59bcddaf678cebeaa838969b67b2d838eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - numpy >=1.22.0

test:
  imports:
    - uniplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/olavolav/uniplot
  summary: Lightweight plotting to the terminal. 4x resolution via Unicode.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
