schema_version: 1

context:
  name: uniplot
  version: "0.21.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/uniplot-${{ version }}.tar.gz
  sha256: ef7e6d5bef477e6e07330d082a24fd0aee9fd5f10a711a2af9ff60d77f391b44

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.22.0
    - readchar >=4.2.1

tests:
  - python:
      imports:
        - uniplot
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Lightweight plotting to the terminal. 4x resolution via Unicode.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/olavolav/uniplot

extra:
  recipe-maintainers:
    - thewchan
